
char *VideoAdapters[] = {"No Video Adapter", "Monochrome Display Adapter",
    "Enhanced Graphics Adapter In Mono Mode", 
    "Multi-Color Graphics Array Adapter Mono Mode", 
    "Video Graphics Array adapter In Mono Mode", "Hercules Graphics Card", 
    "Hercules Graphics Card Plus", "Hercules InColor Card", 
    "Color Graphics Adapter", "Enhanced Graphics Adapter", 
    "Multi-Color Graphics Array Adapter", "Video Graphics Array Adapter"
};

char *MachineType[] = {"Unknown", "IBM PC", "IBM PC/XT, Portable, old Compaq", 
    "IBM PCjr", "IBM PC/AT, XT/286, PS/2 Model 50,60", "IBM PC/XT", 
    "IBM PS/2 model 30", "IBM PC Convertible", "IBM PS/2 model 80", 
    "Sperry PC", "Old Compaq portable", "Old Compaq plus", "HP-110 portable"
};

