@Echo Off
Echo Example 1: Free ? >         Examples.Doc
Echo. >>                         Examples.Doc
Free ? >>                        Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 2: Free /d >>       Examples.Doc
Echo. >>                         Examples.Doc
Free /d >>                       Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 3: Free /f >>       Examples.Doc
Echo. >>                         Examples.Doc
Free /f >>                       Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 4: Free /g >>       Examples.Doc
Echo. >>                         Examples.Doc
Free /g >>                       Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 5: Free /i >>       Examples.Doc
Echo. >>                         Examples.Doc
Free /i >>                       Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 6: Free /d /f /r >> Examples.Doc
Echo. >>                         Examples.Doc
Free /d /f /r >>                 Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 7: Free /g /f /r >> Examples.Doc
Echo. >>                         Examples.Doc
Free /g /f /r >>                 Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
Echo Example 8: Free /i /f >>    Examples.Doc
Echo. >>                         Examples.Doc
Free /i /f >>                    Examples.Doc
Echo. >>                         Examples.Doc
Echo. >>                         Examples.Doc
